/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountsRouteImport } from './routes/_accounts'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AccountsRegisterRouteImport } from './routes/_accounts/register'
import { Route as AccountsLoginRouteImport } from './routes/_accounts/login'
import { Route as AccountsPasswordResetIndexRouteImport } from './routes/_accounts/password/reset/index'
import { Route as AccountsPasswordResetKeyKeyIndexRouteImport } from './routes/_accounts/password/reset/key/$key/index'

const AccountsRoute = AccountsRouteImport.update({
  id: '/_accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AccountsRegisterRoute = AccountsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsLoginRoute = AccountsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsPasswordResetIndexRoute =
  AccountsPasswordResetIndexRouteImport.update({
    id: '/password/reset/',
    path: '/password/reset/',
    getParentRoute: () => AccountsRoute,
  } as any)
const AccountsPasswordResetKeyKeyIndexRoute =
  AccountsPasswordResetKeyKeyIndexRouteImport.update({
    id: '/password/reset/key/$key/',
    path: '/password/reset/key/$key/',
    getParentRoute: () => AccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AccountsLoginRoute
  '/register': typeof AccountsRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/password/reset/': typeof AccountsPasswordResetIndexRoute
  '/password/reset/key/$key/': typeof AccountsPasswordResetKeyKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AccountsLoginRoute
  '/register': typeof AccountsRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/password/reset': typeof AccountsPasswordResetIndexRoute
  '/password/reset/key/$key': typeof AccountsPasswordResetKeyKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_accounts': typeof AccountsRouteWithChildren
  '/_accounts/login': typeof AccountsLoginRoute
  '/_accounts/register': typeof AccountsRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_accounts/password/reset/': typeof AccountsPasswordResetIndexRoute
  '/_accounts/password/reset/key/$key/': typeof AccountsPasswordResetKeyKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/password/reset/'
    | '/password/reset/key/$key/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/password/reset'
    | '/password/reset/key/$key'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_accounts'
    | '/_accounts/login'
    | '/_accounts/register'
    | '/dashboard/'
    | '/_accounts/password/reset/'
    | '/_accounts/password/reset/key/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AccountsRoute: typeof AccountsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_accounts': {
      id: '/_accounts'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_accounts/register': {
      id: '/_accounts/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AccountsRegisterRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/_accounts/login': {
      id: '/_accounts/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AccountsLoginRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/_accounts/password/reset/': {
      id: '/_accounts/password/reset/'
      path: '/password/reset'
      fullPath: '/password/reset/'
      preLoaderRoute: typeof AccountsPasswordResetIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/_accounts/password/reset/key/$key/': {
      id: '/_accounts/password/reset/key/$key/'
      path: '/password/reset/key/$key'
      fullPath: '/password/reset/key/$key/'
      preLoaderRoute: typeof AccountsPasswordResetKeyKeyIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AccountsRouteChildren {
  AccountsLoginRoute: typeof AccountsLoginRoute
  AccountsRegisterRoute: typeof AccountsRegisterRoute
  AccountsPasswordResetIndexRoute: typeof AccountsPasswordResetIndexRoute
  AccountsPasswordResetKeyKeyIndexRoute: typeof AccountsPasswordResetKeyKeyIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsLoginRoute: AccountsLoginRoute,
  AccountsRegisterRoute: AccountsRegisterRoute,
  AccountsPasswordResetIndexRoute: AccountsPasswordResetIndexRoute,
  AccountsPasswordResetKeyKeyIndexRoute: AccountsPasswordResetKeyKeyIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AccountsRoute: AccountsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
