services:
  db:
    image: postgres:latest
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    # image: ghcr.io/danieii/jshipy-server:${GIT_COMMIT_HASH:-latest}
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/app/staticfiles
    env_file:
      .env
    environment:
      - DEBUG=False
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
    
  caddy:
    # image: ghcr.io/danieii/jshipy-caddy:${GIT_COMMIT_HASH:-latest}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/var/www/staticfiles
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server

volumes:
  postgres_data:
  staticfiles:
  dist:
  caddy_data:
  caddy_config:

secrets:
  db-password:
    external: true
