FROM node:20 AS builder

WORKDIR /app

COPY client/package*.json ./

RUN npm ci

COPY ./client ./

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL

RUN npm run build

FROM caddy:latest

COPY --from=builder /app/dist /var/www/dist

COPY ./caddy/Caddyfile.prod /etc/caddy/Caddyfile
